steps:
  build-web:
    image: ruby:latest
    commands:
      - cd web && bundle && bundle exec jekyll build
  build-docs:
    image: mcr.microsoft.com/dotnet/sdk:7.0.305
    commands: 
      - cd docs && dotnet tool restore && dotnet docfx    
  deploy-web:
    image: debian:latest
    when:
      - event: [push, manual]
        branch: main
    commands:
      - rm -rfv /var/www/tinylifegame/*
      - cp -rv web/_site/. /var/www/tinylifegame
    volumes:
      - /var/www/tinylifegame:/var/www/tinylifegame
  deploy-docs:
    image: debian:latest
    when:
      - event: [push, manual]
        branch: main
    commands:
      - rm -rfv /var/www/tinylifedocs/*
      - cp -rv docs/_site/. /var/www/tinylifedocs
    volumes:
      - /var/www/tinylifedocs:/var/www/tinylifedocs
