when:
  path: "web/**"
steps:
  build-web:
    image: ruby:latest
    commands:
      - cd web && bundle && bundle exec jekyll build
  preview-web:
    image: woodpeckerci/plugin-surge-preview
    when:
      event: pull_request
    settings:
      path: web/_site
      surge_token:
        from_secret: surge_token
      forge_type: github
      forge_url: https://github.com
      forge_repo_token:
        from_secret: github_token
  deploy-web:
    image: debian:latest
    when:
      - event: [push, manual]
        branch: main
    commands:
      - rm -rfv /var/www/tinylifegame/*
      - cp -rv web/_site/. /var/www/tinylifegame
    volumes:
      - /var/www/tinylifegame:/var/www/tinylifegame
