### YamlMime:ManagedReference
items:
- uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
  commentId: T:TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
  id: TalkAction.TalkSettings.EvaluationResult
  parent: TinyLife.Actions
  children: []
  langs:
  - csharp
  - vb
  name: TalkAction.TalkSettings.EvaluationResult
  nameWithType: TalkAction.TalkSettings.EvaluationResult
  fullName: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
  type: Delegate
  source:
    remote:
      path: TinyLife/Actions/TalkAction.cs
      branch: master
      repo: https://git.ellpeck.de/Ellpeck/TinyLife.git
    id: EvaluationResult
    path: Actions/TalkAction.cs
    startLine: 376
  assemblies:
  - Tiny Life
  namespace: TinyLife.Actions
  summary: "\nA delegate that is used for <xref href=\"TinyLife.Actions.TalkAction.TalkSettings.Evaluate(TinyLife.Actions.SocialAction)\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: public delegate void EvaluationResult(SocialAction action, ref float romanceGain, ref float friendshipGain, ref float romanceLoss, ref float friendshipLoss, ref float goBadlyChance);
    parameters:
    - id: action
      type: TinyLife.Actions.SocialAction
      description: The action that is being evaluated
    - id: romanceGain
      type: System.Single
      description: The amount of romance points that should be gained as a result of this action succeeding, which already has all default changes applied
    - id: friendshipGain
      type: System.Single
      description: The amount of friendship points that should be gained as a result of this action succeeding, which already has all default changes applied
    - id: romanceLoss
      type: System.Single
      description: The amount of romance points that should be lost as a result of this action going badly, which already has all default changes applied
    - id: friendshipLoss
      type: System.Single
      description: The amount of friendship points that should be lost as a result of this action going badly, which already has all default changes applied
    - id: goBadlyChance
      type: System.Single
      description: The chance, between 0 and 1, that the conversation should end badly. This value already has all of the default changes applied.
    content.vb: Public Delegate Sub EvaluationResult(action As SocialAction, ByRef romanceGain As Single, ByRef friendshipGain As Single, ByRef romanceLoss As Single, ByRef friendshipLoss As Single, ByRef goBadlyChance As Single)
  extensionMethods:
  - TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult.TinyLife.Utilities.Extensions.JsonCopy``1
  modifiers.csharp:
  - public
  - delegate
  modifiers.vb:
  - Public
  - Delegate
references:
- uid: TinyLife.Actions.TalkAction.TalkSettings.Evaluate(TinyLife.Actions.SocialAction)
  commentId: M:TinyLife.Actions.TalkAction.TalkSettings.Evaluate(TinyLife.Actions.SocialAction)
  isExternal: true
- uid: TinyLife.Actions
  commentId: N:TinyLife.Actions
  name: TinyLife.Actions
  nameWithType: TinyLife.Actions
  fullName: TinyLife.Actions
- uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult.TinyLife.Utilities.Extensions.JsonCopy``1
  commentId: M:TinyLife.Utilities.Extensions.JsonCopy``1(``0)
  parent: TinyLife.Utilities.Extensions
  definition: TinyLife.Utilities.Extensions.JsonCopy``1(``0)
  name: JsonCopy<TalkAction.TalkSettings.EvaluationResult>()
  nameWithType: Extensions.JsonCopy<TalkAction.TalkSettings.EvaluationResult>()
  fullName: TinyLife.Utilities.Extensions.JsonCopy<TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult>()
  nameWithType.vb: Extensions.JsonCopy(Of TalkAction.TalkSettings.EvaluationResult)()
  fullName.vb: TinyLife.Utilities.Extensions.JsonCopy(Of TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult)()
  name.vb: JsonCopy(Of TalkAction.TalkSettings.EvaluationResult)()
  spec.csharp:
  - uid: TinyLife.Utilities.Extensions.JsonCopy``1
    name: JsonCopy<TalkAction.TalkSettings.EvaluationResult>
    nameWithType: Extensions.JsonCopy<TalkAction.TalkSettings.EvaluationResult>
    fullName: TinyLife.Utilities.Extensions.JsonCopy<TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: TinyLife.Utilities.Extensions.JsonCopy``1
    name: JsonCopy(Of TalkAction.TalkSettings.EvaluationResult)
    nameWithType: Extensions.JsonCopy(Of TalkAction.TalkSettings.EvaluationResult)
    fullName: TinyLife.Utilities.Extensions.JsonCopy(Of TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: TinyLife.Actions.SocialAction
  commentId: T:TinyLife.Actions.SocialAction
  parent: TinyLife.Actions
  name: SocialAction
  nameWithType: SocialAction
  fullName: TinyLife.Actions.SocialAction
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: Single
  nameWithType: Single
  fullName: System.Single
- uid: TinyLife.Utilities.Extensions.JsonCopy``1(``0)
  commentId: M:TinyLife.Utilities.Extensions.JsonCopy``1(``0)
  name: JsonCopy<T>(T)
  nameWithType: Extensions.JsonCopy<T>(T)
  fullName: TinyLife.Utilities.Extensions.JsonCopy<T>(T)
  nameWithType.vb: Extensions.JsonCopy(Of T)(T)
  fullName.vb: TinyLife.Utilities.Extensions.JsonCopy(Of T)(T)
  name.vb: JsonCopy(Of T)(T)
  spec.csharp:
  - uid: TinyLife.Utilities.Extensions.JsonCopy``1(``0)
    name: JsonCopy<T>
    nameWithType: Extensions.JsonCopy<T>
    fullName: TinyLife.Utilities.Extensions.JsonCopy<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: TinyLife.Utilities.Extensions.JsonCopy``1(``0)
    name: JsonCopy(Of T)
    nameWithType: Extensions.JsonCopy(Of T)
    fullName: TinyLife.Utilities.Extensions.JsonCopy(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: TinyLife.Utilities.Extensions
  commentId: T:TinyLife.Utilities.Extensions
  parent: TinyLife.Utilities
  name: Extensions
  nameWithType: Extensions
  fullName: TinyLife.Utilities.Extensions
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: TinyLife.Utilities
  commentId: N:TinyLife.Utilities
  name: TinyLife.Utilities
  nameWithType: TinyLife.Utilities
  fullName: TinyLife.Utilities
