permalink: devlogs/:title/

defaults:
  - scope:
      type: "posts"
    values:
      layout: "blog"

plugins:
  - jekyll-postfiles
  - jekyll-feed

# markdown formatting
kramdown:
  header_offset: 1
  typographic_syms:
    hellip: ...
    mdash: ---
    ndash: --
    laquo: "<<"
    raquo: ">>"

# atom feed
url: https://tinylifegame.com
title: Tiny Life News and Devlogs
description: News and devlogs for Tiny Life, a fun simulation game where you mess with people's lives
author: Ellpeck Games
feed:
  posts_limit: 10000
