permalink: devlogs/:title/

defaults:
  - scope:
      type: "posts"
    values:
      layout: "blog"

plugins:
  - jekyll-postfiles

# markdown formatting
kramdown:
  header_offset: 1
  typographic_syms:
    hellip: ...
    mdash: ---
    ndash: --
    laquo: "<<"
    raquo: ">>"
